server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/tasktracker?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=x1dHQVdtqLs0KM6F+PMZe5d6zDvtkwVhrKUL6u7wZDwgAaUfF91brhF9Po4YoYdcCjIvZhHTPt7xUJv8jWufAQ==
